/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class FunctorVoid {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FunctorVoid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FunctorVoid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigAndroidGuideJNI.delete_FunctorVoid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected FunctorVoid() {
    wrapper = new FunctorVoidImpl() {
      public void call() {
        FunctorVoid.this.call();
      }
    };
    proxy = new FunctorVoid(wrapper);
  }

  static FunctorVoid makeNative(FunctorVoid in) {
	if (in == null) return null;
    if (null == in.wrapper) return in;
    return in.proxy;
  }

  // Both of these are retained to prevent garbage collection from happenign to early
  private FunctorVoidImpl wrapper;
  private FunctorVoid proxy;

  public FunctorVoid(FunctorVoid arg0) {
    this(SwigAndroidGuideJNI.new_FunctorVoid__SWIG_0(FunctorVoid.getCPtr(arg0), arg0), true);
  }

  public void call() {
    SwigAndroidGuideJNI.FunctorVoid_call(swigCPtr, this);
  }

  public FunctorVoid(SWIGTYPE_p_f___void arg0) {
    this(SwigAndroidGuideJNI.new_FunctorVoid__SWIG_1(SWIGTYPE_p_f___void.getCPtr(arg0)), true);
  }

  public FunctorVoid(FunctorVoidImpl in) {
    this(SwigAndroidGuideJNI.new_FunctorVoid__SWIG_2(FunctorVoidImpl.getCPtr(in), in), true);
  }

}
