/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class IAndroidActivity {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IAndroidActivity(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAndroidActivity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigAndroidGuideJNI.delete_IAndroidActivity(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SwigAndroidGuideJNI.IAndroidActivity_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SwigAndroidGuideJNI.IAndroidActivity_change_ownership(this, swigCPtr, true);
  }

  public void showToast(String value) {
    SwigAndroidGuideJNI.IAndroidActivity_showToast(swigCPtr, this, value);
  }

  public IAndroidActivity() {
    this(SwigAndroidGuideJNI.new_IAndroidActivity(), true);
    SwigAndroidGuideJNI.IAndroidActivity_director_connect(this, swigCPtr, true, true);
  }

}
