/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class ITaskScheduler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ITaskScheduler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ITaskScheduler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigAndroidGuideJNI.delete_ITaskScheduler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SwigAndroidGuideJNI.ITaskScheduler_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SwigAndroidGuideJNI.ITaskScheduler_change_ownership(this, swigCPtr, true);
  }

  public boolean isMainThread() {
    return SwigAndroidGuideJNI.ITaskScheduler_isMainThread(swigCPtr, this);
  }

  public void executeOnBackgroundThread(FunctorVoid function) {
    SwigAndroidGuideJNI.ITaskScheduler_executeOnBackgroundThread(swigCPtr, this, FunctorVoid.getCPtr(FunctorVoid.makeNative(function)), function);
  }

  public void executeOnUIThread(FunctorVoid function) {
    SwigAndroidGuideJNI.ITaskScheduler_executeOnUIThread(swigCPtr, this, FunctorVoid.getCPtr(FunctorVoid.makeNative(function)), function);
  }

  public ITaskScheduler() {
    this(SwigAndroidGuideJNI.new_ITaskScheduler(), true);
    SwigAndroidGuideJNI.ITaskScheduler_director_connect(this, swigCPtr, true, true);
  }

}
