/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class shared_ptr_to_string {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected shared_ptr_to_string(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(shared_ptr_to_string obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigAndroidGuideJNI.delete_shared_ptr_to_string(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public shared_ptr_to_string() {
    this(SwigAndroidGuideJNI.new_shared_ptr_to_string(), true);
  }

}
