/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class SwigAndroidGuideJNI {
  public final static native void ActivityModel_onCreate(long jarg1, ActivityModel jarg1_);
  public final static native void ActivityModel_setMultiplier(long jarg1, ActivityModel jarg1_, int jarg2);
  public final static native int ActivityModel_multiply__SWIG_0(long jarg1, ActivityModel jarg1_, int jarg2);
  public final static native int ActivityModel_multiply__SWIG_1(int jarg1, int jarg2);
  public final static native long new_ActivityModel();
  public final static native void delete_ActivityModel(long jarg1);
}
