/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class SwigAndroidGuideJNI {
  public final static native long new_Multiply(int jarg1);
  public final static native int Multiply_multiply__SWIG_0(long jarg1, Multiply jarg1_, int jarg2);
  public final static native int Multiply_multiply__SWIG_1(int jarg1, int jarg2);
  public final static native void delete_Multiply(long jarg1);
}
