/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class VectorByte extends java.util.AbstractList<Short> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorByte(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorByte obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigAndroidGuideJNI.delete_VectorByte(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorByte(short[] initialElements) {
    this();
    reserve(initialElements.length);

    for (short element : initialElements) {
      add(element);
    }
  }

  public VectorByte(Iterable<Short> initialElements) {
    this();
    for (short element : initialElements) {
      add(element);
    }
  }

  public Short get(int index) {
    return doGet(index);
  }

  public Short set(int index, Short e) {
    return doSet(index, e);
  }

  public boolean add(Short e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Short e) {
    modCount++;
    doAdd(index, e);
  }

  public Short remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorByte() {
    this(SwigAndroidGuideJNI.new_VectorByte__SWIG_0(), true);
  }

  public VectorByte(VectorByte other) {
    this(SwigAndroidGuideJNI.new_VectorByte__SWIG_1(VectorByte.getCPtr(other), other), true);
  }

  public long capacity() {
    return SwigAndroidGuideJNI.VectorByte_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigAndroidGuideJNI.VectorByte_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigAndroidGuideJNI.VectorByte_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigAndroidGuideJNI.VectorByte_clear(swigCPtr, this);
  }

  public VectorByte(int count, short value) {
    this(SwigAndroidGuideJNI.new_VectorByte__SWIG_2(count, value), true);
  }

  private int doSize() {
    return SwigAndroidGuideJNI.VectorByte_doSize(swigCPtr, this);
  }

  private void doAdd(short x) {
    SwigAndroidGuideJNI.VectorByte_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, short x) {
    SwigAndroidGuideJNI.VectorByte_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private short doRemove(int index) {
    return SwigAndroidGuideJNI.VectorByte_doRemove(swigCPtr, this, index);
  }

  private short doGet(int index) {
    return SwigAndroidGuideJNI.VectorByte_doGet(swigCPtr, this, index);
  }

  private short doSet(int index, short val) {
    return SwigAndroidGuideJNI.VectorByte_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SwigAndroidGuideJNI.VectorByte_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
