/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class VectorVectorByte extends java.util.AbstractList<VectorByte> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorVectorByte(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorVectorByte obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigAndroidGuideJNI.delete_VectorVectorByte(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorVectorByte(VectorByte[] initialElements) {
    this();
    reserve(initialElements.length);

    for (VectorByte element : initialElements) {
      add(element);
    }
  }

  public VectorVectorByte(Iterable<VectorByte> initialElements) {
    this();
    for (VectorByte element : initialElements) {
      add(element);
    }
  }

  public VectorByte get(int index) {
    return doGet(index);
  }

  public VectorByte set(int index, VectorByte e) {
    return doSet(index, e);
  }

  public boolean add(VectorByte e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, VectorByte e) {
    modCount++;
    doAdd(index, e);
  }

  public VectorByte remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorVectorByte() {
    this(SwigAndroidGuideJNI.new_VectorVectorByte__SWIG_0(), true);
  }

  public VectorVectorByte(VectorVectorByte other) {
    this(SwigAndroidGuideJNI.new_VectorVectorByte__SWIG_1(VectorVectorByte.getCPtr(other), other), true);
  }

  public long capacity() {
    return SwigAndroidGuideJNI.VectorVectorByte_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigAndroidGuideJNI.VectorVectorByte_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigAndroidGuideJNI.VectorVectorByte_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigAndroidGuideJNI.VectorVectorByte_clear(swigCPtr, this);
  }

  public VectorVectorByte(int count, VectorByte value) {
    this(SwigAndroidGuideJNI.new_VectorVectorByte__SWIG_2(count, VectorByte.getCPtr(value), value), true);
  }

  private int doSize() {
    return SwigAndroidGuideJNI.VectorVectorByte_doSize(swigCPtr, this);
  }

  private void doAdd(VectorByte x) {
    SwigAndroidGuideJNI.VectorVectorByte_doAdd__SWIG_0(swigCPtr, this, VectorByte.getCPtr(x), x);
  }

  private void doAdd(int index, VectorByte x) {
    SwigAndroidGuideJNI.VectorVectorByte_doAdd__SWIG_1(swigCPtr, this, index, VectorByte.getCPtr(x), x);
  }

  private VectorByte doRemove(int index) {
    return new VectorByte(SwigAndroidGuideJNI.VectorVectorByte_doRemove(swigCPtr, this, index), true);
  }

  private VectorByte doGet(int index) {
    return new VectorByte(SwigAndroidGuideJNI.VectorVectorByte_doGet(swigCPtr, this, index), false);
  }

  private VectorByte doSet(int index, VectorByte val) {
    return new VectorByte(SwigAndroidGuideJNI.VectorVectorByte_doSet(swigCPtr, this, index, VectorByte.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SwigAndroidGuideJNI.VectorVectorByte_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
