/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.goldberg.swigandroidguide.swiggenerated;

public class VideoMessage extends Message {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected VideoMessage(long cPtr, boolean cMemoryOwn) {
    super(SwigAndroidGuideJNI.VideoMessage_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        SwigAndroidGuideJNI.delete_VideoMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public VideoMessage(int id, java.lang.String text) {
    this(SwigAndroidGuideJNI.new_VideoMessage(id, text), true);
  }

  public byte[][] getVideoChunks() {
     return SwigAndroidGuideJNI.VideoMessage_getVideoChunks(swigCPtr, this);
}

  public void setVideoChunks(byte[][] videoChunks) {
    SwigAndroidGuideJNI.VideoMessage_setVideoChunks(swigCPtr, this, videoChunks);
  }

  public static VideoMessage dynamic_cast(Message arg) {
    long cPtr = SwigAndroidGuideJNI.VideoMessage_dynamic_cast(Message.getCPtr(arg), arg);
    return (cPtr == 0) ? null : new VideoMessage(cPtr, true);
  }

}
